spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=false
    username: root
    password: sai123baba
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: product

  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka

server:
  port: ${PORT:0}

application:
  bucket:
    name: ea-final-project-bucket

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: ABCD
      secretKey: EFGH

#spring.jpa.hibernate.use-new-id-generator-mappings=false
#logging.level.root=WARN